export const SFL_PROCUREMENT_COURSE_URL = "https://sfl-public-procurement.lucia20200524.chatgpt.site";
export const SFL_AI_COURSE_URL = "https://sfl-codex-app-bootcamp.lucia20200524.chatgpt.site/";
export const SFL_LARK_TRAINING_URL = "https://sfl-reskilling-2026.lucia20200524.chatgpt.site/#lark";

export const SFL_COURSES = [
  {
    id: "lark-intro",
    name: "SFL Lark導入講座",
    status: "0期生終了・1期生進行中・次回2期生募集",
    audience: "個人向け講座",
    type: "individual",
    topic: "LARK",
    usesLark: true,
    description: "基本操作からBaseの設計・構築まで、仕事で使うLarkのスキルを学びます。",
    href: "/lark-dx#individual-course",
    action: "講座の内容・料金を見る",
  },
  {
    id: "lark-dx-training",
    name: "SFL DX(Lark)研修",
    audience: "法人向け研修",
    type: "corporate",
    topic: "LARK",
    usesLark: true,
    description: "法人向けリスキリングのLark研修。自社業務を題材に、Lark・Baseによる業務改善と仕組みづくりを実践します。",
    href: SFL_LARK_TRAINING_URL,
    external: true,
    action: "Lark研修の詳細を見る",
  },
  {
    id: "ai-course",
    name: "SFL AI導入講座",
    status: "2026年10月開始",
    audience: "個人向け講座",
    type: "individual",
    topic: "AI",
    usesLark: false,
    description: "AI・プログラミング初心者向け。ChatGPTで保存なしWebアプリをつくる体験編4時間から、希望者はCodexで保存機能の実装・公開を学ぶ仕事編6時間へ。オンラインで段階的に学びます。",
    href: SFL_AI_COURSE_URL,
    external: true,
    action: "体験編・仕事編の詳細を見る",
  },
  {
    id: "ai-training",
    name: "SFL AI研修",
    audience: "法人向け研修",
    type: "corporate",
    topic: "AI",
    usesLark: false,
    description: "調査・資料作成・業務改善からWebアプリ制作まで、自社業務での生成AI活用を学びます。",
    href: "/ai-dx-training",
    action: "研修のカリキュラムを見る",
  },
  {
    id: "public-procurement-course",
    name: "SFL 官公庁入札講座",
    status: "2026年10月開始",
    audience: "個人向け講座",
    type: "individual",
    topic: "官公庁入札",
    usesLark: false,
    description: "官公庁入札について学ぶ実務講座です。講座内容・受講方法は専用の案内ページをご覧ください。",
    href: SFL_PROCUREMENT_COURSE_URL,
    external: true,
    action: "入札講座の案内を見る",
  },
] as const;
